name: CI/CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  pipeline:
    uses: ArchGenTf/Main/.github/workflows/backend.yml@master
    with:
      service: "auth-service"
      image: "acrarchgen.azurecr.io/auth-service"
      trigger: ${{ github.event_name }}
    secrets: inherit
